<script setup>
import { computed, onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import StatusBadge from '../components/StatusBadge.vue';
import { platformApi } from '../platformApi.js';
import { dateOnly, money } from '../utils/format.js';

const route = useRoute();
const detail = ref(null);
const error = ref('');
const paid = computed(() => detail.value?.payments.reduce((sum, payment) => sum + payment.amountCents, 0) || 0);
const printInvoice = () => window.print();
onMounted(async () => {
  try { detail.value = await platformApi.get(`/invoices/${route.params.id}`); } catch (e) { error.value = e.message; }
});
</script>

<template>
  <div class="invoice-toolbar">
    <router-link class="btn btn-outline" :to="{ name: 'platform-billing' }">Back to billing</router-link>
    <button class="btn btn-primary" @click="printInvoice">Print / save PDF</button>
  </div>
  <p v-if="error" class="error-text">{{ error }}</p>
  <article v-else-if="detail" class="invoice">
    <header>
      <div><h1>e<em>Wash</em></h1><p>Laundry Management SaaS</p></div>
      <div class="invoice-title"><span>INVOICE</span><b>{{ detail.invoice.number }}</b><StatusBadge :status="detail.invoice.status" kind="generic" /></div>
    </header>
    <section class="meta">
      <div><span>Bill to</span><b>{{ detail.invoice.tenantName }}</b><p>{{ detail.invoice.billingEmail || 'Billing contact not provided' }}</p></div>
      <div><span>Issued</span><b>{{ dateOnly(detail.invoice.issuedAt) }}</b><span>Due</span><b>{{ dateOnly(detail.invoice.dueAt) }}</b></div>
    </section>
    <table>
      <thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead>
      <tbody><tr v-for="item in detail.items" :key="item.id"><td>{{ item.description }}</td><td>{{ item.quantity }}</td><td>{{ money(item.unitAmountCents, detail.invoice.currency) }}</td><td>{{ money(item.lineTotalCents, detail.invoice.currency) }}</td></tr></tbody>
    </table>
    <section class="totals">
      <div><span>Subtotal</span><b>{{ money(detail.invoice.subtotalCents, detail.invoice.currency) }}</b></div>
      <div><span>Tax</span><b>{{ money(detail.invoice.taxCents, detail.invoice.currency) }}</b></div>
      <div><span>Paid</span><b>{{ money(paid, detail.invoice.currency) }}</b></div>
      <div class="grand"><span>Balance due</span><b>{{ money(detail.invoice.totalCents - paid, detail.invoice.currency) }}</b></div>
    </section>
    <footer><p v-if="detail.invoice.notes">{{ detail.invoice.notes }}</p><small>Generated by eWash Laundry Management System</small></footer>
  </article>
  <p v-else class="muted">Loading invoice…</p>
</template>

<style scoped>
.invoice-toolbar{display:flex;justify-content:flex-end;gap:8px;margin-bottom:14px}.invoice{max-width:850px;margin:auto;padding:34px 40px;background:#fff;border:1px solid var(--line);border-radius:14px;box-shadow:var(--shadow-card)}header{display:flex;justify-content:space-between;gap:24px;padding-bottom:22px;border-bottom:2px solid var(--side)}h1{margin:0;font:800 25px var(--font-ui)}h1 em{color:var(--brand);font-style:normal}header p,.meta p{margin:2px 0;color:var(--muted);font-size:11px}.invoice-title{text-align:right}.invoice-title>span{display:block;color:var(--muted);font-size:10px;letter-spacing:.14em}.invoice-title>b{display:block;margin:3px 0 7px;font-size:17px}.meta{display:flex;justify-content:space-between;gap:24px;padding:22px 0}.meta>div:last-child{display:grid;grid-template-columns:auto auto;gap:3px 16px;text-align:right}.meta span{display:block;color:var(--muted);font-size:9.5px;text-transform:uppercase}.meta b{font-size:12px}table{width:100%;border-collapse:collapse;font-size:12px}th{padding:9px;text-align:left;color:var(--muted);font-size:9.5px;text-transform:uppercase;border-bottom:1px solid var(--line)}th:not(:first-child),td:not(:first-child){text-align:right}td{padding:12px 9px;border-bottom:1px solid #edf2f1}.totals{width:310px;margin:20px 0 26px auto}.totals div{display:flex;justify-content:space-between;padding:5px 0;font-size:11.5px}.totals .grand{margin-top:5px;padding-top:10px;border-top:2px solid var(--side);font-size:14px}footer{padding-top:15px;border-top:1px solid var(--line);color:var(--muted);font-size:10px}
@media(max-width:640px){.invoice{padding:22px 18px;border-radius:10px}.meta{display:block}.meta>div+div{margin-top:15px}.totals{width:100%}}
@media print{.invoice-toolbar{display:none}.invoice{max-width:none;padding:0;border:0;box-shadow:none}.invoice{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style>
