import pathlib

reps = [
    ("'Branch updated'", "'Filial atualizada'"),
    ("'Branch created'", "'Filial criada'"),
    ("'Last order'", "'Último pedido'"),
    ("'Lifetime value'", "'Valor acumulado'"),
    ("'Handed over'", "'Entregue'"),
    ("'Confirm password'", "'Confirmar senha'"),
    ("'Total invoiced'", "'Total faturado'"),
    ("'Closed invoices'", "'Faturas fechadas'"),
    ("'Ready since'", "'Pronto desde'"),
    ("'Active invoices'", "'Faturas ativas'"),
    ("'Income collected'", "'Receita recebida'"),
    ("'Show closed'", "'Mostrar fechadas'"),
    ("'Hide closed'", "'Ocultar fechadas'"),
    ("'Pickup history'", "'Histórico de coletas'"),
    ("'View all'", "'Ver tudo'"),
    ("'Finished orders'", "'Pedidos concluídos'"),
    ("'Void expense'", "'Anular despesa'"),
    ("'Money earned'", "'Receita ganha'"),
    ("'Customer created'", "'Cliente criado'"),
    ("'Paid via'", "'Pago via'"),
    ("'Service type'", "'Tipo de serviço'"),
    ("'Edit provider'", "'Editar fornecedor'"),
    ("'Closed orders'", "'Pedidos fechados'"),
    ("'Reset password'", "'Redefinir senha'"),
    ("'Good morning'", "'Bom dia'"),
    ("'Good evening'", "'Boa noite'"),
    ("'Good afternoon'", "'Boa tarde'"),
    ("'Update expense'", "'Atualizar despesa'"),
    ("'Save expense'", "'Salvar despesa'"),
    ("'Tenant revenue'", "'Receita da loja'"),
    ("'Open menu'", "'Abrir menu'"),
    ("'Edit expense'", "'Editar despesa'"),
    ("'Add expense'", "'Nova despesa'"),
    ("'New password'", "'Nova senha'"),
    ("'Financial health'", "'Saúde financeira'"),
    ("'Retire service'", "'Desativar serviço'"),
    ("'Category name'", "'Nome da categoria'"),
    ("'New category'", "'Nova categoria'"),
    # Platform UI
    ("'Platform owner'", "'Dono da plataforma'"),
    ("'Tenant created'", "'Loja criada'"),
    ("'Suspended'", "'Suspenso'"),
    ("'Active tenants'", "'Lojas ativas'"),
    ("'Trial tenants'", "'Lojas em teste'"),
    ("'Suspended tenants'", "'Lojas suspensas'"),
    ("'Cancelled tenants'", "'Lojas canceladas'"),
    ("'New tenant'", "'Nova loja'"),
    ("'Edit tenant'", "'Editar loja'"),
    ("'Tenant name'", "'Nome da loja'"),
    ("'Billing email'", "'E-mail de cobrança'"),
    ("'Subscription plan'", "'Plano de assinatura'"),
    ("'Trial days'", "'Dias de teste'"),
    ("'Outstanding balance'", "'Saldo pendente'"),
    ("'Platform revenue'", "'Receita da plataforma'"),
    ("'Monthly recurring'", "'Recorrência mensal'"),
    ("'New plan'", "'Novo plano'"),
    ("'Plan created'", "'Plano criado'"),
    ("'Plan updated'", "'Plan atualizado'"),
    ("'Invoice issued'", "'Fatura emitida'"),
    ("'Payment recorded'", "'Pagamento registrado'"),
    ("'Payment voided'", "'Pagamento anulado'"),
    ("'Record payment'", "'Registrar pagamento'"),
    ("'Issue invoice'", "'Emitir fatura'"),
    ("'Invoice description'", "'Descrição da fatura'"),
    ("'Due date'", "'Vencimento'"),
    ("'Amount due'", "'Valor a pagar'"),
    ("'Tax'", "'Imposto'"),
    ("'Save plan'", "'Salvar plano'"),
    ("'New user'", "'Novo usuário'"),
    ("'User created'", "'Usuário criado'"),
    ("'Edit user'", "'Editar usuário'"),
    ("'Role name'", "'Nome do papel'"),
    ("'New role'", "'Novo papel'"),
    ("'Create role'", "'Criar papel'"),
    ("'Branch name'", "'Nome da filial'"),
    ("'Location'", "'Localização'"),
    ("'Add branch'", "'Adicionar filial'"),
    ("'New branch'", "'Nova filial'"),
    ("'Branch access'", "'Acesso da filial'"),
    ("'Sign in'", "'Entrar'"),
    ("'Sign out'", "'Sair'"),
    ("'Sign in with Google'", "'Entrar com Google'"),
    ("'Sign in to your account'", "'Entre na sua conta'"),
    ("'Sign in to the platform console'", "'Acesse o painel da plataforma'"),
    ("'Forgot password'", "'Esqueceu a senha'"),
    ("'Back to sign in'", "'Voltar ao login'"),
    ("'Email address'", "'Endereço de e-mail'"),
    ("'Phone number'", "'Número de telefone'"),
    ("'Full name'", "'Nome completo'"),
    ("'Notes'", "'Observações'"),
    ("'Order code'", "'Código do pedido'"),
    ("'Order status'", "'Status do pedido'"),
    ("'Payment status'", "'Status do pagamento'"),
    ("'Payment method'", "'Método de pagamento'"),
    ("'Payment amount'", "'Valor do pagamento'"),
    ("'Payment reference'", "'Referência do pagamento'"),
    ("'Amount paid'", "'Valor pago'"),
    ("'Balance due'", "'Saldo devedor'"),
    ("'Customer name'", "'Nome do cliente'"),
    ("'Add customer'", "'Adicionar cliente'"),
    ("'Edit customer'", "'Editar cliente'"),
    ("'Customer updated'", "'Cliente atualizado'"),
    ("'No customers yet'", "'Nenhum cliente ainda'"),
    ("'No orders yet'", "'Nenhum pedido ainda'"),
    ("'No notifications'", "'Sem notificações'"),
    ("'Search customers'", "'Buscar clientes'"),
    ("'Search orders'", "'Buscar pedidos'"),
    ("'Search branches'", "'Buscar filiais'"),
    ("'Filter by status'", "'Filtrar por status'"),
    ("'All statuses'", "'Todos os status'"),
    ("'Select branch'", "'Selecionar filial'"),
    ("'Assess order'", "'Avaliar pedido'"),
    ("'Reassess order'", "'Reavaliar pedido'"),
    ("'Order assessed'", "'Pedido avaliado'"),
    ("'Confirm order'", "'Confirmar pedido'"),
    ("'Close order'", "'Fechar pedido'"),
    ("'Order closed'", "'Pedido fechado'"),
    ("'Void order'", "'Cancelar pedido'"),
    ("'Order voided'", "'Pedido cancelado'"),
    ("'Mark delivered'", "'Marcar como entregue'"),
    ("'Mark ready'", "'Marcar como pronto'"),
    ("'Start washing'", "'Iniciar lavagem'"),
    ("'Start ironing'", "'Iniciar passadoria'"),
    ("'Express handling'", "'Atendimento expresso'"),
    ("'Discount'", "'Desconto'"),
    ("'Total'", "'Total'"),
    ("'Subtotal'", "'Subtotal'"),
    ("'Express fee'", "'Taxa expressa'"),
    ("'Service name'", "'Nome do serviço'"),
    ("'Service created'", "'Serviço criado'"),
    ("'Service updated'", "'Serviço atualizado'"),
    ("'Build services'", "'Construir serviços'"),
    ("'Pricing model'", "'Modelo de preço'"),
    ("'Base rate'", "'Tarifa base'"),
    ("'Minimum charge'", "'Cobrança mínima'"),
    ("'Unit'", "'Unidade'"),
    ("'Variant label'", "'Rótulo da variação'"),
    ("'Variant price'", "'Preço da variação'"),
    ("'Add variant'", "'Adicionar variação'"),
    ("'New addon'", "'Novo adicional'"),
    ("'Tier min qty'", "'Qtd. mínima da faixa'"),
    ("'Tier rate'", "'Tarifa da faixa'"),
    ("'Band price'", "'Preço da faixa'"),
    ("'Dashboard'", "'Painel'"),
    ("'Orders'", "'Pedidos'"),
    ("'Customers'", "'Clientes'"),
    ("'Finance'", "'Financeiro'"),
    ("'Reports'", "'Relatórios'"),
    ("'Users & roles'", "'Usuários e papéis'"),
    ("'Branches'", "'Filiais'"),
    ("'Settings'", "'Configurações'"),
    ("'Tenants'", "'Lojas'"),
    ("'Plans & pricing'", "'Planos e preços'"),
    ("'Accounting'", "'Contabilidade'"),
    ("'Audit log'", "'Registro de auditoria'"),
    ("'Revenue'", "'Receita'"),
    ("'Billing'", "'Cobrança'"),
    ("'Invoices'", "'Faturas'"),
    ("'Collect'", "'Coletar'"),
    ("'Deliver'", "'Entregar'"),
    ("'Receive order'", "'Receber pedido'"),
    ("'Order received'", "'Pedido recebido'"),
    ("'Send notification'", "'Enviar notificação'"),
    ("'Notification sent'", "'Notificação enviada'"),
    ("'Message preview'", "'Pré-visualização da mensagem'"),
    ("'Record payment'", "'Registrar pagamento'"),
    ("'Refund payment'", "'Estornar pagamento'"),
    ("'Paid in full'", "'Pago integralmente'"),
    ("'Partially paid'", "'Pago parcialmente'"),
    ("'Unpaid'", "'Não pago'"),
    ("'Paid'", "'Pago'"),
    ("'Cash'", "'Dinheiro'"),
    ("'Bank transfer'", "'Transferência bancária'"),
    ("'Credit customer'", "'Cliente a prazo'"),
    ("'Credit limit'", "'Limite de crédito'"),
    ("'Credit terms'", "'Prazo de crédito'"),
    ("'Expense category'", "'Categoria de despesa'"),
    ("'Expense date'", "'Data da despesa'"),
    ("'Expense amount'", "'Valor da despesa'"),
    ("'Recurring expense'", "'Despesa recorrente'"),
    ("'Receipt attached'", "'Comprovante anexado'"),
    ("'Daily register'", "'Caixa diário'"),
    ("'Daily totals'", "'Totais do dia'"),
    ("'Profit & loss'", "'Lucros e perdas'"),
    ("'Net profit'", "'Lucro líquido'"),
    ("'Gross revenue'", "'Receita bruta'"),
    ("'Total expenses'", "'Total de despesas'"),
    ("'Revenue by category'", "'Receita por categoria'"),
    ("'Top services'", "'Serviços mais vendidos'"),
    ("'Orders this month'", "'Pedidos do mês'"),
    ("'Revenue this month'", "'Receita do mês'"),
    ("'This week'", "'Esta semana'"),
    ("'This month'", "'Este mês'"),
    ("'Last month'", "'Mês passado'"),
    ("'Select dates'", "'Selecionar datas'"),
    ("'Export CSV'", "'Exportar CSV'"),
    ("'Need help'", "'Precisa de ajuda'"),
    ("'Cancel'", "'Cancelar'"),
    ("'Save'", "'Salvar'"),
    ("'Delete'", "'Excluir'"),
    ("'Edit'", "'Editar'"),
    ("'Add'", "'Adicionar'"),
    ("'Confirm'", "'Confirmar'"),
    ("'No results'", "'Sem resultados'"),
    ("'Everything is caught up'", "'Tudo em dia'"),
    ("'Nothing to show'", "'Nada para mostrar'"),
    ("'Platform overview'", "'Visão geral da plataforma'"),
    ("'Recent registrations'", "'Registros recentes'"),
    ("'Monthly income'", "'Receita mensal'"),
    ("'Annual recurring'", "'Recorrência anual'"),
    ("'Operating revenue'", "'Receita operacional'"),
    ("'Collections'", "'Recebimentos'"),
    ("'Tenant performance'", "'Desempenho das lojas'"),
    ("'Activate account'", "'Ativar conta'"),
    ("'Choose your password'", "'Escolha sua senha'"),
    ("'Your laundry is live'", "'Sua lavanderia está no ar'"),
    ("'Adjust prices'", "'Ajustar preços'"),
    ("'Service Builder'", "'Construtor de Serviços'"),
    ("'Add service'", "'Novo serviço'"),
    ("'Edit service'", "'Editar serviço'"),
    ("'Service catalog'", "'Catálogo de serviços'"),
    ("'Template catalog'", "'Catálogo modelo'"),
    ("'Welcome'", "'Bem-vindo'"),
    ("'Signed in as'", "'Logado como'"),
    ("'Platform console'", "'Painel da plataforma'"),
    ("'Tenant application'", "'Aplicativo da loja'"),
    ("'Per kg'", "'Por kg'"),
    ("'Per item'", "'Por peça'"),
    ("'Flat rate'", "'Valor fixo'"),
    ("'Tiered pricing'", "'Preço por faixa'"),
    ("'Active'", "'Ativo'"),
    ("'Inactive'", "'Inativo'"),
    ("'Suspend tenant'", "'Suspender loja'"),
    ("'Reactivate tenant'", "'Reativar loja'"),
    ("'Tenant suspended'", "'Loja suspensa'"),
    ("'Tenant reactivated'", "'Loja reativada'"),
    ("'Suspend reason'", "'Motivo da suspensão'"),
    ("'Plan price'", "'Preço do plano'"),
    ("'Term (months)'", "'Prazo (meses)'"),
    ("'Trial plan'", "'Plano de teste'"),
    ("'Grace period'", "'Período de carência'"),
    ("'Grace ends'", "'Carência termina'"),
    ("'Trial ends'", "'Teste termina'"),
    ("'Cancelled'", "'Cancelado'"),
    ("'Cancel subscription'", "'Cancelar assinatura'"),
    ("'Subscription cancelled'", "'Assinatura cancelada'"),
    ("'Reason'", "'Motivo'"),
    ("'Features'", "'Recursos'"),
    ("'Code prefix'", "'Prefixo do código'"),
    ("'Business name'", "'Nome do negócio'"),
    ("'Business phone'", "'Telefone do negócio'"),
    ("'Save settings'", "'Salvar configurações'"),
    ("'Settings saved'", "'Configurações salvas'"),
    ("'Message templates'", "'Modelos de mensagem'"),
    ("'Save templates'", "'Salvar modelos'"),
    ("'Templates saved'", "'Modelos salvos'"),
    ("'Notifications'", "'Notificações'"),
    ("'SMS disabled'", "'SMS desativado'"),
    ("'Audit',", "'Auditoria',"),
    ("'Actions',", "'Ações',"),
    ("'Actor'", "'Ator'"),
    ("'Entity'", "'Entidade'"),
    ("'Details'", "'Detalhes'"),
    ("'When'", "'Quando'"),
    ("'No audit entries'", "'Sem registros de auditoria'"),
    ("'Paid invoices'", "'Faturas pagas'"),
    ("'Overdue invoices'", "'Faturas vencidas'"),
    ("'Outstanding'", "'Pendente'"),
    ("'Mark paid'", "'Marcar como pago'"),
    ("'Void invoice'", "'Anular fatura'"),
    ("'Invoice voided'", "'Fatura anulada'"),
    ("'Draft invoices'", "'Faturas em rascunho'"),
    ("'Issued invoices'", "'Faturas emitidas'"),
    ("'Issued at'", "'Emitida em'"),
    ("'Paid at'", "'Paga em'"),
    ("'Payments on invoice'", "'Pagamentos da fatura'"),
    ("'Method'", "'Método'"),
    ("'Reference'", "'Referência'"),
    ("'Paid at date'", "'Data do pagamento'"),
    ("'Revenue by tenant'", "'Receita por loja'"),
    ("'Top tenants'", "'Lojas com maior receita'"),
    ("'Platform profit'", "'Lucro da plataforma'"),
    ("'Closed revenue'", "'Receita fechada'"),
    ("'Open revenue'", "'Receita em aberto'"),
    ("'You do not have permission'", "'Você não tem permissão'"),
    ("'Access denied'", "'Acesso negado'"),
    ("'Locked'", "'Bloqueado'"),
    ("'Unlock with password'", "'Desbloquear com senha'"),
    ("'Wrong password'", "'Senha incorreta'"),
    ("'Invalid credentials'", "'Credenciais inválidas'"),
    ("'Account not activated'", "'Conta não ativada'"),
    ("'Account activated'", "'Conta ativada'"),
    ("'Password updated'", "'Senha atualizada'"),
    ("'Password reset requested'", "'Redefinição de senha solicitada'"),
    ("'Check your email'", "'Verifique seu e-mail'"),
    ("'Something went wrong'", "'Algo deu errado'"),
    ("'Order not found'", "'Pedido não encontrado'"),
    ("'Customer not found'", "'Cliente não encontrado'"),
    ("'Branch not found'", "'Filial não encontrada'"),
    ("'User not found'", "'Usuário não encontrado'"),
    ("'Loading…'", "'Carregando…'"),
    ("'No items yet'", "'Sem itens ainda'"),
    ("'Quantity'", "'Quantidade'"),
    ("'Unit price'", "'Preço unitário'"),
    ("'Line total'", "'Total da linha'"),
    ("'Item removed'", "'Item removido'"),
    ("'Add item'", "'Adicionar item'"),
    ("'Assessment notes'", "'Observações da avaliação'"),
    ("'Send WhatsApp'", "'Enviar WhatsApp'"),
    ("'Send SMS'", "'Enviar SMS'"),
    ("'Message sent'", "'Mensagem enviada'"),
    ("'History'", "'Histórico'"),
    ("'Rewash order'", "'Relavar pedido'"),
    ("'Collected by'", "'Coletado por'"),
    ("'Collected at'", "'Coletado em'"),
    ("'Delivery due'", "'Entrega prevista'"),
    ("'Due at'", "'Previsto para'"),
    ("'Express order'", "'Pedido expresso'"),
    ("'Handoff type'", "'Tipo de entrega'"),
    ("'Pickup'", "'Coleta'"),
    ("'Delivery',", "'Entrega',"),
    ("'Pickups'", "'Coletas'"),
    ("'Pending pickups'", "'Coletas pendentes'"),
    ("'Todays pickups'", "'Coletas de hoje'"),
    ("'Schedule pickup'", "'Agendar coleta'"),
    ("'Pickup scheduled'", "'Coleta agendada'"),
    ("'Mark collected'", "'Marcar como coletado'"),
    ("'Collected'", "'Coletado'"),
    ("'All pickups'", "'Todas as coletas'"),
    ("'Assigned rider'", "'Entregador atribuído'"),
    ("'Rider'", "'Entregador'"),
    ("'Riders'", "'Entregadores'"),
    ("'Add rider'", "'Adicionar entregador'"),
    ("'Edit rider'", "'Editar entregador'"),
    ("'Rider created'", "'Entregador criado'"),
    ("'Rider updated'", "'Entregador atualizado'"),
]

targets = list(pathlib.Path('web/src/views').glob('*.vue')) + \
          list(pathlib.Path('web/src/components').glob('*.vue')) + \
          [pathlib.Path('web/src/utils/format.js')]

changed = []
for p in targets:
    t = p.read_text()
    o = t
    for a, b in reps:
        t = t.replace(a, b)
    if t != o:
        p.write_text(t)
        changed.append(p.name)

print('Arquivos alterados:', len(changed))
for c in sorted(set(changed)):
    print(' -', c)
